### PR TITLE
New Crowdin translations (target: 0.1.2)

### PR DESCRIPTION
**Pull request by Anoyomouse**
Enjoy!

### CODE REVIEW

**Comment by dgw** [comment]
Lol, Crowdin is calling it `locale.ini` even though that's not the file name 😆

**Comment by Anoyomouse** [comment]
I had to call it locale.ini to force the file type filter to pick things up right

BTW, we already have a new shiny German translation already!

**Comment by dgw** [comment]
@Anoyomouse Are you able to rebase this onto current master to get rid of the `crowdin.yml` commits? I'm guessing this PR shouldn't touch the Crowdin config file at all because the one you committed to `master` works the way it's supposed to? (If you can't rebase but can answer that question, I can do the rebase. :smile_cat:)

**Comment by Anoyomouse** [comment]
@dgw it's easier if you flatten it out, this Pr was created by crowdin directly, so not sure how to flatten it out from their side

**Comment by dgw** [comment]
Straightened out the config file commits. Should I also flatten the commits down to one per language? Maybe pull the latest changes from Crowdin into this PR before I do that? (Can Crowdin update existing PRs? I hope so. If not, that's kind of messy! 😆 )

**Comment by dgw** [comment]
Got Crowdin to push the latest changes. Its commit messages bother me, because they don't need to include the filename (we have only one file per language) and the filename it does include is _wrong_ lol. :/

**Comment by dgw** [comment]
Squashed for sanity…

**Comment by Anoyomouse** [comment]
Loaded up my source control manager and managed to squash the commits (for real this time), and merge the main branch back into this one, should be good for merging for 1.2.0 now

**Comment by dgw** [comment]
We should **never** merge `master` into topic branches. PR branches can be rebased onto it though, but it's only necessary if something in `master` causes a merge conflict.

That said, I will probably restore the squashed history I created the other day, because having separate commits per language will be helpful when building the changelog for release.

**Comment by dgw** [comment]
> also, we ened to check the BOM isn't included when dealing with UTF-8, as factorio doesn't load weird BoM marked files for translations

I opened every locale file in the PR (at present) in hex mode and there is no BOM at the top of any of them. :raised_hands: Just going to play with switching locales next time I run the game to make sure the new locales load properly, then we should be ready to :ship: :shipit:

Removing "do not merge" label now though. It should be technically all set, and I hope to get this merged in tonight after testing (then finish the changelog and release).

**Pull request merged**
