### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Anoyomouse**
Enjoy!

### CODE REVIEW

**Comment by dgw** [comment]
But I just merged this! :grin:

Maybe we should switch to translation pull…

**Comment by Anoyomouse** [comment]
Can't help that the new version has pulled in more translations

Maybe we should set it up that you pull the translations on build rather .. though i love seeing the translations pop in

**Comment by dgw** [comment]
Squash, squash, squash... I wish Crowdin would intelligently condense stuff like identical changes made to every language into a single commit.

**Comment by dgw** [comment]
Decided to start editing the credits into the commit history directly while I squash. Should make writing the changelog easier...

**Pull request merged**
