### PR TITLE
Packaging powered by make

### PR DESCRIPTION
**Pull request by dgw**
This packaging system worked flawlessly to release the last two builds of Warehousing; big thanks to @narc0tiq for the [factorio-mod-makefile](https://github.com/narc0tiq/factorio-mod-makefile) project!

I meant to push this up months ago, but got distracted by other projects after releasing 0.0.13 and wound up never doing so.

The one thing I'm not happy with is `Readme.md` displaying "**Current version: {{VERSION}}**" instead of the real (development) version number. However, making it display the actual version would require updating both `VERSION` and `Readme.md` at each bump, which somewhat defeats the purpose of having a `VERSION` file in the first place. Thoughts, @Anoyomouse? Could use `bumpversion` to update both files with one command, I suppose, but that would require a Python environment in addition to `make`.

### CODE REVIEW

**Comment by Anoyomouse** [comment]
Hmmm ....

I would probably have written a whole pythojn script to do the packaging for me, and then extend that to do the readme and all the packaging, so instead of needing make (a pain in most OSes - except linux - to use python exclusively, because that's how I rolll

However as you're building the mod, it needs to be easy for you to do the builds and deployments.

I do agree with you that the Readme with a {{VERSION}} is a little dodgy .. how about a plan b, you have readme.template, that gets built into README.md when you build the project, that way in the git repo you have an up to date version number when working on the project (also bearing in mind the version should only be updated when a new version is released - it does say "Current version" .. you can change it to "latest released version", and have that only update when we release?

**Comment by dgw** [comment]
Well, the Makefile was already written :P

I might play with the readme template idea, but isn't the readme more for the repo than anything else? Doesn't look like it's pulled into the mod portal for use as the mod description or anything fancy like that, so is there really any point in putting the version number in the readme at all? Just a thought, in case I can't find a solution I'm happy with. :)

**Comment by narc0tiq** [comment]
Glad you liked the project! The setup with the files on disk is actually based on @FunnyMan3595's [mcp_rebuild](https://github.com/FunnyMan3595/mcp_rebuild), a (now fairly outdated) setup for building Minecraft mods. Entertainingly, that one *was* a python script. I just used `make` because it was handy.


> `Readme.md` displaying "Current version: {{VERSION}}"

Personally, I keep the version out of the README, but that's just because I'm too lazy to remember to update *two* files (the reason for making the mod makefile to begin with).


> also bearing in mind the version should only be updated when a new version is released - it does say "Current version"

Hmm, I read "current version" as meaning "the version in this package". It couldn't be referring to the actual latest, since you keep a copy of the README in each release, right?

**Comment by dgw** [comment]
Right, there is a copy of the readme in the mod release package. And that's what the "Current version" string is meant for, in case the zipfile name has been mangled somehow (so the user doesn't have to dig into `info.json` or `control.lua`).

I guess I'm not really _that_ bothered either way. The version string can stay, or not. It's just a convenience, which is probably not useful in 99% of cases anyway.

**Comment by Anoyomouse** [comment]
Well, i like people being able to look at the git repo and seeing "oh the released version is x.x.x", at least it gives them a guide to what to look for (on the mod portal or in game)

It's always weird when the repo is like 2 versions ahead of what's released

That being said, we really don't need to update it, so if you don't work it out, then we can remove it (and yes, it's mainly just for the repo, but it's there to help people if they stumble on it)

Also, thanks @narc0tiq for the makefile

TBH, if you make a python script you could just drive it off the info.json, but that requires some writing

**Comment by dgw** [comment]
Oh wait, I could probably manage a badge in the readme that displays the most recent release tag. That'd take care of it for sure, so that'll be my fallback plan.

**Comment by Anoyomouse** [comment]
@dgw I think ;et's just do a badge for the current stable release

For simplicity here's the Markdown!

[release](https://github.com/anoyomouse/warehousing/releases/latest)

**Comment by dgw** [comment]
@Anoyomouse I'll work on that soon-ish. Will probably end up restructuring the readme a bit (again) to make the badge fit nicely, and might also put that off until the buffer warehouses are done.

**Comment by dgw** [comment]
I need to sort out my default push branch for `master` lol. That's gotta be the third time this week I pushed intending for it to go to this repo but it went to mine instead.

This PR wound up including the Readme badges, so I guess #28 is redundant now, whoops.

**Pull request merged**
